language: python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION="Django>=1.11,<2"
  - DJANGO_VERSION="Django>=2.0,<3"
  - DJANGO_VERSION="Django>=3.0,<4"

install:
  - pip install pyquery
  - pip install -q $DJANGO_VERSION
  - pip install coverage

script: coverage run quicktest.py multi_email_field.tests

after_success:
 - pip install coveralls
 - coveralls

# We need to exclude old versions of Python for tests with Django >= 2
matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION="Django>=2.0,<3"
        - python: 2.7
          env: DJANGO_VERSION="Django>=3.0,<4"
